import { WasmState } from '../types';
import { writeString } from './helpers';

/**
 * No-op stubs for all frame.canvas bridge functions.
 *
 * frame.canvas is a client-only Layer 4 plugin: canvas drawing, audio,
 * and input are handled in the browser. However, WASM modules that use
 * canvasScene: blocks emit imports for every _canvas_*, _input_*,
 * _audio_*, _sprite_*, etc. bridge function regardless of whether the
 * module ultimately runs server-side.
 *
 * Without these stubs, WebAssembly.instantiate fails with LinkError
 * whenever the host loads a .wasm that has any canvas scene in it.
 *
 * This file registers a no-op for every bridge entry declared in
 * clean-framework/plugins/frame.canvas/plugin.toml [bridge]. The
 * signatures match the plugin.toml declarations exactly so the linker
 * is satisfied. None of these stubs perform any work — canvas scenes
 * are not executed server-side.
 *
 * Mirrors clean-server/src/bridge_canvas_stubs.rs.
 */
export function createCanvasClientStubs(
  getState: () => WasmState
): Record<string, (...args: number[]) => number | void> {
  return {
    _canvas_init(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _canvas_clear(_p0: number): number { return 0; },
    _canvas_clear_color(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_present(_p0: number): number { return 0; },
    _canvas_set_fps(_p0: number, _p1: number): number { return 0; },
    _canvas_resize(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_get_width(_p0: number): number { return 0; },
    _canvas_get_height(_p0: number): number { return 0; },
    _canvas_request_frame(_p0: number): number { return 0; },
    _canvas_cancel_frame(_p0: number): number { return 0; },
    _canvas_get_delta_time(): number { return 0; },
    _canvas_get_time(): number { return 0; },
    _canvas_get_fps(): number { return 0; },
    _canvas_var_set(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_var_get(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_circle_filled(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _canvas_circle_outline(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _canvas_rect_filled(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_rect_outline(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_rect_rounded(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number): number { return 0; },
    _canvas_line(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number): number { return 0; },
    _canvas_triangle_filled(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number): number { return 0; },
    _canvas_triangle_outline(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number): number { return 0; },
    _canvas_ellipse_filled(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_ellipse_outline(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_text(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number): number { return 0; },
    _canvas_text_aligned(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number, _p9: number, _p10: number, _p11: number): number { return 0; },
    _canvas_text_width(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _canvas_image(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_image_opacity(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number): number { return 0; },
    _canvas_image_cropped(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number, _p9: number): number { return 0; },
    _canvas_image_rotated(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_save(_p0: number): number { return 0; },
    _canvas_restore(_p0: number): number { return 0; },
    _canvas_translate(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_rotate(_p0: number, _p1: number): number { return 0; },
    _canvas_scale(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_transform(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_reset_transform(_p0: number): number { return 0; },
    _canvas_alpha_begin(_p0: number, _p1: number): number { return 0; },
    _canvas_alpha_end(_p0: number): number { return 0; },
    _canvas_shadow_begin(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _canvas_shadow_end(_p0: number): number { return 0; },
    _canvas_blur_begin(_p0: number, _p1: number): number { return 0; },
    _canvas_blur_end(_p0: number): number { return 0; },
    _canvas_glow_begin(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _canvas_glow_end(_p0: number): number { return 0; },
    _canvas_blend_begin(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_blend_end(_p0: number): number { return 0; },
    _canvas_set_alpha(_p0: number, _p1: number): number { return 0; },
    _canvas_set_blend_mode(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_set_shadow(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _canvas_clear_shadow(_p0: number): number { return 0; },
    _canvas_set_line_cap(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_set_line_join(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_set_line_dash(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_clear_line_dash(_p0: number): number { return 0; },
    _canvas_begin_path(_p0: number): number { return 0; },
    _canvas_move_to(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_line_to(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_curve_to(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _canvas_cubic_to(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_arc(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _canvas_arc_to(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _canvas_close_path(_p0: number): number { return 0; },
    _canvas_fill_path(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_stroke_path(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _canvas_draw_named_path(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _gradient_linear(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _gradient_radial(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _gradient_add_stop(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _gradient_ref(_p0: number, _p1: number): number { return 0; },
    _layer_declare(_p0: number, _p1: number, _p2: number): number { return 0; },
    _layer_begin(_p0: number, _p1: number): number { return 0; },
    _layer_end(): number { return 0; },
    _sprite_load_sheet(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _sprite_draw(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number): number { return 0; },
    _sprite_draw_flipped(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number, _p9: number): number { return 0; },
    _sprite_get_frame_count(_p0: number): number { return 0; },
    _sprite_get_frame_width(_p0: number): number { return 0; },
    _sprite_get_frame_height(_p0: number): number { return 0; },
    _anim_sprite_draw(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _anim_sprite_draw_ex(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number): number { return 0; },
    _anim_sprite_reset(_p0: number, _p1: number): number { return 0; },
    _tween_play(_p0: number, _p1: number): number { return 0; },
    _tween_stop(_p0: number, _p1: number): number { return 0; },
    _tween_pause(_p0: number, _p1: number): number { return 0; },
    _tween_resume(_p0: number, _p1: number): number { return 0; },
    _tween_animate(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _timeline_play(_p0: number, _p1: number): number { return 0; },
    _timeline_stop(_p0: number, _p1: number): number { return 0; },
    _timeline_pause(_p0: number, _p1: number): number { return 0; },
    _timeline_seek(_p0: number, _p1: number, _p2: number): number { return 0; },
    _anim_state_start(_p0: number, _p1: number): number { return 0; },
    _anim_state_force(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _anim_state_current(_p0: number, _p1: number): number { return writeString(getState(), ''); },
    _particles_emit(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _particles_start(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _particles_stop(_p0: number, _p1: number): number { return 0; },
    _canvas_on_pointer_down(_p0: number): number { return 0; },
    _canvas_on_pointer_move(_p0: number): number { return 0; },
    _canvas_on_pointer_up(_p0: number): number { return 0; },
    _canvas_on_key_down(_p0: number): number { return 0; },
    _canvas_on_key_up(_p0: number): number { return 0; },
    _canvas_event_x(): number { return 0; },
    _canvas_event_y(): number { return 0; },
    _canvas_event_key(): number { return writeString(getState(), ''); },
    _input_mouse_x(): number { return 0; },
    _input_mouse_y(): number { return 0; },
    _input_mouse_pressed(_p0: number): number { return 0; },
    _input_mouse_just_pressed(_p0: number): number { return 0; },
    _input_mouse_just_released(_p0: number): number { return 0; },
    _input_mouse_wheel_y(): number { return 0; },
    _input_key_down(_p0: number, _p1: number): number { return 0; },
    _input_key_just_pressed(_p0: number, _p1: number): number { return 0; },
    _input_key_just_released(_p0: number, _p1: number): number { return 0; },
    _input_get_last_key(): number { return writeString(getState(), ''); },
    _input_touch_count(): number { return 0; },
    _input_touch_x(_p0: number): number { return 0; },
    _input_touch_y(_p0: number): number { return 0; },
    _input_gamepad_connected(_p0: number): number { return 0; },
    _input_gamepad_button(_p0: number, _p1: number): number { return 0; },
    _input_gamepad_axis(_p0: number, _p1: number): number { return 0; },
    _input_gamepad_left_stick_x(_p0: number): number { return 0; },
    _input_gamepad_left_stick_y(_p0: number): number { return 0; },
    _input_gamepad_right_stick_x(_p0: number): number { return 0; },
    _input_gamepad_right_stick_y(_p0: number): number { return 0; },
    _audio_play_sound(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _audio_preload(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _audio_stop(_p0: number): number { return 0; },
    _audio_pause(_p0: number): number { return 0; },
    _audio_resume(_p0: number): number { return 0; },
    _audio_is_playing(_p0: number): number { return 0; },
    _audio_music_play(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _audio_music_stop(_p0: number, _p1: number): number { return 0; },
    _audio_music_pause(_p0: number, _p1: number): number { return 0; },
    _audio_music_resume(_p0: number, _p1: number): number { return 0; },
    _audio_music_fade_out(_p0: number, _p1: number, _p2: number): number { return 0; },
    _audio_music_crossfade(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _audio_music_set_volume(_p0: number, _p1: number, _p2: number): number { return 0; },
    _audio_set_master_volume(_p0: number): number { return 0; },
    _audio_mute(): number { return 0; },
    _audio_unmute(): number { return 0; },
    _audio_is_muted(): number { return 0; },
    _collision_circles(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _collision_rects(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number): number { return 0; },
    _collision_point_rect(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _collision_circle_rect(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _collision_point_circle(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _collision_ray_circle(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _asset_load_image(_p0: number, _p1: number): number { return 0; },
    _asset_load_sound(_p0: number, _p1: number): number { return 0; },
    _asset_load_music(_p0: number, _p1: number): number { return 0; },
    _asset_queue(_p0: number, _p1: number): number { return 0; },
    _asset_load_all(): number { return 0; },
    _asset_get_progress(): number { return 0; },
    _asset_all_loaded(): number { return 0; },
    _asset_get(_p0: number, _p1: number): number { return 0; },
    _asset_unload(_p0: number): number { return 0; },
    _camera_set_position(_p0: number, _p1: number): number { return 0; },
    _camera_get_x(): number { return 0; },
    _camera_get_y(): number { return 0; },
    _camera_set_zoom(_p0: number): number { return 0; },
    _camera_get_zoom(): number { return 0; },
    _camera_set_rotation(_p0: number): number { return 0; },
    _camera_set_follow(_p0: number, _p1: number, _p2: number): number { return 0; },
    _camera_set_offset(_p0: number, _p1: number): number { return 0; },
    _camera_set_deadzone(_p0: number, _p1: number): number { return 0; },
    _camera_set_bounds(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _camera_apply(_p0: number): number { return 0; },
    _camera_reset(_p0: number): number { return 0; },
    _camera_screen_to_world_x(_p0: number): number { return 0; },
    _camera_screen_to_world_y(_p0: number): number { return 0; },
    _camera_shake(_p0: number, _p1: number, _p2: number): number { return 0; },
    _ease_linear(_p0: number): number { return 0; },
    _ease_cubic_in(_p0: number): number { return 0; },
    _ease_cubic_out(_p0: number): number { return 0; },
    _ease_cubic_in_out(_p0: number): number { return 0; },
    _ease_in_quad(_p0: number): number { return 0; },
    _ease_out_quad(_p0: number): number { return 0; },
    _ease_in_out_quad(_p0: number): number { return 0; },
    _ease_in_sine(_p0: number): number { return 0; },
    _ease_out_sine(_p0: number): number { return 0; },
    _ease_in_out_sine(_p0: number): number { return 0; },
    _ease_in_expo(_p0: number): number { return 0; },
    _ease_out_expo(_p0: number): number { return 0; },
    _ease_in_out_expo(_p0: number): number { return 0; },
    _ease_elastic_out(_p0: number): number { return 0; },
    _ease_elastic_in(_p0: number): number { return 0; },
    _ease_bounce_out(_p0: number): number { return 0; },
    _ease_bounce_in(_p0: number): number { return 0; },
    _ease_back_out(_p0: number): number { return 0; },
    _ease_back_in(_p0: number): number { return 0; },
    _ease_back_in_out(_p0: number): number { return 0; },
    _ease_in_out_elastic(_p0: number): number { return 0; },
    _ease_in_out_bounce(_p0: number): number { return 0; },
    _canvas_group_begin(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_group_end(_p0: number): number { return 0; },
    _canvas_clip_rect(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _canvas_clip_circle(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _canvas_clip_path(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_clip_end(_p0: number): number { return 0; },
    _font_load(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _canvas_text_font(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number, _p9: number, _p10: number, _p11: number, _p12: number): number { return 0; },
    _custom_ease_register(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _ease_custom(_p0: number, _p1: number, _p2: number): number { return 0; },
    _canvas_rect_gradient(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_circle_gradient(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _canvas_fill_path_gradient(_p0: number, _p1: number, _p2: number): number { return 0; },
    _sprite_draw_tint(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number, _p9: number, _p10: number): number { return 0; },
    _sprite_draw_state(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _tween_animate_path(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _canvas_on_exit(_p0: number): number { return 0; },
    _canvas_on_pause(_p0: number): number { return 0; },
    _canvas_on_resume(_p0: number): number { return 0; },
    _scene_get_current(): number { return writeString(getState(), ''); },
    _scene_change(_p0: number, _p1: number): number { return 0; },
    _scene_change_animated(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number): number { return 0; },
    _scene_push(_p0: number, _p1: number): number { return 0; },
    _scene_pop(): number { return 0; },
    _scene_set(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _scene_get(_p0: number, _p1: number): number { return writeString(getState(), ''); },
    _page_set(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _page_get(_p0: number, _p1: number): number { return writeString(getState(), ''); },
    _asset_preload_image(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _sprite_register_sheet(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _animsprite_define(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number): number { return 0; },
    _tween_define_var(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number, _p8: number, _p9: number, _p10: number, _p11: number, _p12: number, _p13: number): number { return 0; },
    _path_begin(_p0: number, _p1: number): number { return 0; },
    _path_move_to(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _path_line_to(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _path_curve_to(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number): number { return 0; },
    _path_cubic_to(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number, _p7: number): number { return 0; },
    _path_arc_to(_p0: number, _p1: number, _p2: number, _p3: number, _p4: number, _p5: number, _p6: number): number { return 0; },
    _path_close(_p0: number, _p1: number): number { return 0; },
    _timeline_define_json(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _animstate_define_json(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
    _particles_define_json(_p0: number, _p1: number, _p2: number, _p3: number): number { return 0; },
  };
}
